# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{better_delegation}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh N. Abbott"]
  s.date = %q{2009-11-11}
  s.description = %q{Calling a delegated method on a nil object with better_delegation won't just return nil, it will return the default database column value. Eg. If is_active is a boolean field and it's database default value is 'false', calling the delegated method when the delegated asssociation is nil won't return nil, it will return false. This is reflected in the tests.}
  s.email = %q{joshnabbott@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/better_delegation.rb",
     "spec/better_delegation_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/joshnabbott/better_delegation}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Extends the Object#delegate method to work better with `nil` objects.}
  s.test_files = [
    "spec/better_delegation_spec.rb",
     "spec/db/schema.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
